"""Generate the mining golden fixture for the web wallet's test suite.

Run from a checkout that has the ``scarletcoin`` package installed (for example
the ScarletCoin repository, using ``uv run python``)::

    uv run python tools/generate_mining_fixture.py

It writes ``test/fixtures/mining.json``.  The web wallet's
``test/mining.test.ts`` rebuilds the block from the template and must reproduce
the node's block hash and bytes exactly.  This pins two things that mining
depends on and that drift silently otherwise:

* the block layout (header, transactions, coinbase, Merkle root), and
* the header timestamp — which must be the template's ``current_time``, because
  the node derives the required difficulty from the child block's timestamp.
"""

from __future__ import annotations

import json
from pathlib import Path

from scarletcoin.core.template import BlockTemplate
from scarletcoin.core.transaction import OutPoint, Transaction, TxInput, TxOutput

OUT = Path(__file__).resolve().parents[1] / "test" / "fixtures" / "mining.json"


def main() -> None:
    prev_hash = bytes(range(32))
    key_hash = bytes.fromhex("00112233445566778899aabbccddeeff00112233")
    extra = bytes([0xAA, 0xBB, 0xCC, 0xDD])

    # One mempool-style transaction, carrying a witness so the wallet's
    # serialised-txid parser is exercised too.
    spend = Transaction(
        version=1,
        inputs=(
            TxInput(
                OutPoint(bytes(range(32, 64)), 1),
                0xFFFFFFFE,
                (b"\x02" + b"\x11" * 32, b"\x30" * 64),
            ),
        ),
        outputs=(TxOutput.p2pkh(123456789, key_hash),),
        lock_time=0,
    )

    template = BlockTemplate(
        height=5000,
        prev_hash=prev_hash,
        bits=0x207FFFFF,  # easy target: any nonce meets it
        min_time=1_700_000_000,
        current_time=1_700_000_060,
        coinbase_value=5_000_000_000 + 1234,
        transactions=(spend,),
        version=1,
    )

    block = template.build_block(
        pubkey_hash=key_hash, extra=extra, timestamp=template.current_time, nonce=0
    )
    fixture = {
        "note": (
            "Generated by scarletcoin.core.template.BlockTemplate.build_block;"
            " the web wallet must reproduce it byte-for-byte, using current_time"
            " as the header timestamp."
        ),
        "template": template.to_dict(),
        "pubkey_hash": key_hash.hex(),
        "extra_nonce": extra.hex(),
        "nonce": 0,
        "timestamp": template.current_time,
        "block_hash": block.hash_hex(),
        "block_hex": block.serialize().hex(),
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(fixture, indent=2) + "\n", "utf-8")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()